# Generated by Django 3.2.3 on 2022-11-04 19:22

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_app', '0003_alter_reminder_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='threshold',
            field=models.PositiveSmallIntegerField(null=True, validators=[common.validators.check_threshold], verbose_name='Threshold'),
        ),
    ]
