# Generated by Django 3.2.3 on 2022-11-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_app', '0004_alter_reminder_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
